title: site
extends: layouts/page

tabs:
  content:
    columns:
      content:
        sections:
          message:
            type: fields
            fields:
              message:
                type: text
                size: tiny
                maxlength: 32
          posts:
            extends: sections/posts
          projects:
            extends: sections/projects
      sidebar:
        sections:
          settings:
            type: fields
            fields:
              pagination:
                type: number
                default: 10
                required: true
              copyright_start_year:
                label: Copyright start year
                type: number

  theme: tabs/theme
